// Generated by sama-packages/scripts/export-api-types.mjs from sama-packages/api-types/src/types.ts.
// Do not edit here: change api-types and rerun the script, so sama-backend and sama-frontend keep one definition.
/**
 * Wire shapes between sama-frontend and sama-backend. The backend builds every response through these types
 * (sama-backend/src/lib/{views,circle-view,market,targets}.ts) and the frontend reads them; a change here breaks whichever side is out of date at compile time.
 * Fields marked optional were added after the frontend's first version, so an older client still parses responses.
 */

export type AssetClass = "STOCK" | "ETF" | "CASH";

/**
 * A: PancakeSwap pool + TWAP, price cross-checked on-chain, leftovers can be swapped.
 * B: Binance price only, leftovers carry forward. C: same as B, but a counterparty is unlikely (few holders or leveraged).
 */
export type AssetTier = "A" | "B" | "C";

export type Asset = {
  /** `${chainId}:${checksumAddress}` — the symbol is display only (PRD §7.1). */
  uid: string;
  address: `0x${string}`;
  symbol: string;
  name: string;
  decimals: number;
  class: AssetClass;
  priceUsd: number;
  disclosure?: string;
  tier?: AssetTier;
  /** Leveraged or inverse ETF: decays when held, so the UI warns before it goes into a target. */
  leveraged?: boolean;
  /** BEP-8056 UI multiplier: shares per raw token. Wallets show raw balance × multiplier. */
  uiMultiplier?: number;
  /** Logo served by the frontend or an absolute URL; absent means a monogram. */
  logoUrl?: string;
};

export type Position = { symbol: string; amountTokens: number; valueUsd: number; pct: number };

export type Portfolio = { ok: true; totalUsd: number; readAt: string; positions: Position[] } | { ok: false; detail: string };

export type ResidualStyle = "ECONOMIC" | "CARRY_FORWARD" | "CANCEL";

export type Target = { weights: Record<string, number>; costCapBps: number; residualStyle: ResidualStyle; savedAt: string };

export type TargetPreview = { ok: boolean; problems: string[]; trades: Array<{ symbol: string; side: Side; amountTokens: number; valueUsd: number }> };

/** Time windows for the portfolio value chart. */
export type HistoryRange = "1H" | "1D" | "1W" | "1M" | "1Y" | "ALL";

/** One point of total wallet value: `t` in ms since epoch, `usd` the total at that moment. Oldest first. */
export type HistoryPoint = { t: number; usd: number };

export type Drift = { symbol: string; currentPct: number; targetPct: number };

export type Visibility = "PUBLIC" | "INVITE_ONLY" | "PRIVATE";

export type RoundState =
  | "DRAFT" | "OPEN" | "COLLECTING" | "FROZEN" | "SOLVING" | "PROPOSED" | "APPROVING" | "READY_TO_SETTLE"
  | "SETTLING" | "SETTLED" | "RESIDUAL_EXECUTION" | "VERIFYING" | "COMPLETE"
  | "EXPIRED" | "INSUFFICIENT_PARTICIPANTS" | "NO_CROSS" | "PLAN_REJECTED" | "PLAN_STALE" | "SETTLEMENT_REVERTED"
  | "RESIDUAL_PARTIAL" | "RESIDUAL_FAILED" | "VERIFICATION_FAILED" | "CANCELLED";

export type Circle = {
  id: string;
  name: string;
  description: string;
  visibility: Visibility;
  assetSymbols: string[];
  cadenceSec: number | null;
  durationSec: number;
  minParticipants: number;
  memberCount: number;
  residualBehavior: ResidualStyle;
  role: "ORGANIZER" | "MEMBER" | null;
  liveRound: { id: string; sequence: number; state: RoundState; freezesAt: number } | null;
  nextRoundAt: string | null;
  history: Array<{ id: string; sequence: number; state: RoundState; crossedUsd: number; endedAt: string }>;
};

/** What an invite link opens, readable before sign-in (GET /api/invites/:code). */
export type InviteInfo = { circleId: string; circleName: string; used: boolean };

export type NewCircle = Pick<Circle, "name" | "description" | "visibility" | "assetSymbols" | "cadenceSec" | "durationSec" | "minParticipants" | "residualBehavior">;

export type Side = "SELL" | "BUY";
export type ResidualChoice = "CARRY_FORWARD" | "EXECUTE_NOW" | "CANCEL";
export type EngineDecision = "EXECUTE_NOW" | "LIMIT" | "TWAP" | "WAIT" | "AGGREGATE" | "CANCEL";

/**
 * `id` is the stable check key the frontend translates (e.g. "calldata.plan", "event.NonceConsumed"); `name` is an
 * English label for clients that do not know the id.
 */
export type VerifierCheck = { id?: string; name: string; status: "PASS" | "FAIL" | "INCONCLUSIVE"; detail: string };

export type RoundView = {
  round: {
    id: string;
    sequence: number;
    state: RoundState;
    terminal: boolean;
    freezesAt: number;
    snapshotHash: string;
    prices: Array<{ symbol: string; priceUsd: number; source?: "BINANCE+TWAP" | "BINANCE" | "FIXED"; uiMultiplier?: number }>;
    /** Assets the snapshot left out of this round, with the reason the user sees. */
    excludedAssets?: Array<{ symbol: string; reason: string }>;
    /** NYSE session at snapshot time; "closed" means stock prices are the last close. */
    marketSession?: "market" | "extended" | "overnight" | "closed";
    settlementContract: `0x${string}`;
    settlementTx: `0x${string}` | null;
    planHash: string | null;
    planValidUntil: number | null;
    history: Array<{ state: RoundState; at: string; reason: string | null }>;
    verification: {
      status: "PASS" | "FAIL" | "INCONCLUSIVE";
      blockNumber: string | null;
      checks: VerifierCheck[];
      providers: { executor: string; verifier: string; independent: boolean } | null;
    } | null;
  };
  circle: { id: string; name: string; assetSymbols: string[]; minParticipants: number; memberCount: number; residualBehavior: ResidualStyle; isOrganizer: boolean };
  you: {
    signed: boolean;
    intent: Array<{ symbol: string; side: Side; amountTokens: number; valueUsd: number }>;
    outsideCircle: string[];
    legs: Array<{ direction: "SEND" | "RECEIVE"; counterparty: string; symbol: string; amountTokens: number; valueUsd: number }>;
    inPlan: boolean;
    approved: boolean;
    allowances: Array<{ token: `0x${string}`; symbol: string; amountRaw: bigint; amountTokens: number; sufficient: boolean; funded: boolean }>;
    residual: Array<{ symbol: string; side: Side; amountTokens: number; valueUsd: number; dust: boolean }>;
    recommendation: { decision: EngineDecision | null; reasons: string[]; canExecute: boolean; costPct: number | null } | null;
    decision: { choice: ResidualChoice; txHash: string | null } | null;
    /** Why the viewer cannot sign into this round right now (no target, nothing held, outside the circle), or null. */
    joinBlocker?: string | null;
  };
  aggregate: { signed: number; participants: number; approvals: number; requestedUsd: number; crossedUsd: number; residualUsd: number; crossRateBps: number; legCount: number; cycleCount: number };
  /** Gas for approve and settle is paid by the paymaster when true (PRD §6.3). */
  gasSponsored: boolean;
};

export type Activity = { id: string; kind: string; detail: Record<string, string | number>; roundId: string | null; createdAt: string };

export type PendingRound = {
  roundId: string;
  circleName: string;
  state: RoundState;
  freezesAt: number;
  signed: boolean;
  approved: boolean;
  inPlan: boolean;
  residualUndecidedUsd: number;
};

export type Home = {
  portfolio: Portfolio;
  target: Target | null;
  drift: Drift[];
  totalDriftPct: number;
  circles: Circle[];
  activity: Activity[];
  pending: PendingRound[];
};

export type Settings = { notify: { email: boolean; telegram: boolean; inApp: boolean }; residualStyle: ResidualStyle; costCapBps: number; gasSponsorship: boolean };

export type Session = { address: `0x${string}`; demo: boolean };

/** Public evidence for /proof: the deployed contract and every settled round. No participant addresses. */
export type Proof = {
  chainId: number;
  settlement: { address: `0x${string}`; deployTx: string | null; deployBlock: number | null; verifiedSource: boolean };
  rounds: Array<{
    roundId: string;
    /** Public circles by name; private and invite-only circles stay anonymous. */
    circleName: string | null;
    sequence: number;
    state: RoundState;
    settledAt: string;
    settlementTx: string;
    participants: number;
    legCount: number;
    cycleCount: number;
    crossedUsd: number;
    verification: { status: "PASS" | "FAIL" | "INCONCLUSIVE"; passed: number; total: number; providersIndependent: boolean; pricesIndependent: boolean } | null;
  }>;
};
